### ISSUE TITLE
Usage in stateless components

### ISSUE THREAD

**Issue by livioso** [devBrian/react-native-dropdownalert#1]
Is there any plan / way to use this in stateless components? 🤔

`<DropdownAlert ref={"dropdownalert"} />`

Will not work when used in a stateless component such as 
```
const User = ({ props }) => {
  ...
    <DropdownAlert ref={"dropdownalert"} />`
  ...
};
```

Thanks in advance. :)

**Comment by devBrian** [comment]
@livioso Do you know why it does not work in the stateless environment? Or is it simply that this is not stateless and just will not cooperate? I will take a look as well. I do plan to try to move to stateless and ES6 syntax.

**Comment by devBrian** [comment]
I will run some tests and see what's involved to get his working in a stateless environment.

**Comment by devBrian** [comment]
I guess what I meant by run some tests was more like find out about stateless components. So I found out that stateless component **can't have the ref** so my take is that can't you just drop it from your implementation there? Or am I misunderstanding something here?

**Comment by devBrian** [comment]
Closing due to no response. But thanks for your feedback. welcome to re-open if you want to discuss further.
