### ISSUE TITLE
[Feature-request] optional button on right side or left side

### ISSUE THREAD

**Issue by devBrian** [devBrian/react-native-dropdownalert#10]
Like it could be a close button so that It would give the user a better indicator to tap it to close. Or an action like delete or invite or go to XYZ location, etc. 

**What do others think about this? Open to suggestions**

**Comment by teyou** [comment]
I think it is alright, as long as it wont block user to keep interacting with the UI while showing the DropdownAlert.
like something shows here [RKDropdownAlert](https://medium.com/@cwRichardKim/devux-uialertview-alternatives-3a78ab64cbf8#.fe244vw0b)

**Comment by devBrian** [comment]
Yeah I agree. #7 would help address this.

**Comment by devBrian** [comment]
Not going to do this.
