### ISSUE TITLE
fontSize should be configurable

### ISSUE THREAD

**Issue by steida** [devBrian/react-native-dropdownalert#11]
The correct approach is to allow custom styles for everything.
Check https://facebook.github.io/react-native/docs/text.html#style

**Comment by steida** [comment]
Also I think the modal is unnecessary. It should be implemented via CSS zIndex.

**Comment by devBrian** [comment]
I agree. Something like titleStyle, messageStyle, imageStyle and containerStyle would be nice and would help scale the component better.

**Comment by devBrian** [comment]
Yeah the zIndex was just recently added was my only concern, I think RN 0.29.  But almost a week into RN 0.30 so I think it's time to move to that.

**Comment by devBrian** [comment]
I will get to both of these a little later this week if not sooner. Thanks for the feedback

**Comment by devBrian** [comment]
I am going wait to introduce the zIndex. Track issue #7 for when this will be supported.
