### ISSUE TITLE
[Feedback] Release / Usage 1.9.0

### ISSUE THREAD

**Issue by devBrian** [devBrian/react-native-dropdownalert#12]
Hi, all. I'm glad everyone is enjoying the component as much as I do developing it. I was wondering if I was overzealous in this release. I did a major update to the props in turn allowing more flexibly and I was wonder if this eases implementation or causes more of a headache and if it should be simplified in the future.  Let me know what you think. Thanks.

**Comment by DavyDeDurpel** [comment]
I just only discovered this plug-in today so I have no experience with the previous properties.  For me the current properties are clear and easy to use.  

I do have a remark about the 'ref' attribute.  In your example it's a string but the new preferred way is to use a callback as such:

ref={(alert) => this._alert = alert}

And I was also wondering if in your current implementation it would be possible to simulate that beautiful IOS transition effect.  Their effect is like pulling a drawer and then turning it.  That would make it perfect ;-)

**Comment by devBrian** [comment]
Oh that's interesting: `ref={(alert) => this._alert = alert}` what's the back story on this? Oh like some spring end transition to give it a little bounce? Thanks for the feedback.

**Comment by DavyDeDurpel** [comment]
I think the main reason is that they no longer want to have 'refs' as a React reserved property.  And in my short experience with React Native, I noticed that 'this.refs' often resulted in 'undefined' while defining my own callback method did not have this issue.
