### ISSUE TITLE
other UI components are not responding when the dropdown alert is on the view

### ISSUE THREAD

**Issue by ismdcf** [devBrian/react-native-dropdownalert#17]
Once the dropdown alert is shown all the other components that are in the view cannot be interacted until the dropdown alert is closed. it looks like the whole screen has been taken by the dropdown alert which is not a good experience for the user .

**Comment by devBrian** [comment]
Yes, this was solved with (Look into zIndex as a possible replacement of modal #7) I recommend to upgrade to 1.10.0 and move the component to the last position in the document tree.

**Comment by ismdcf** [comment]
Cool Updated to 1.10.0 and it works like a charm 👍  💯  thanks @devBrian
