### ISSUE TITLE
onClose prop not fired from timeout

### ISSUE THREAD

**Issue by tapdancemobile** [devBrian/react-native-dropdownalert#20]
#### Issue Description

The onClose callback is not called upon the timer expiring

#### Steps to Reproduce / Code Snippets

	render() {

		const route = this.props.navigation.routes[this.props.navigation.index];

		return (
			<View style={styles.main}>
				<DropdownAlert
					ref={(ref) => this.dropdown = ref} onClose={(data) => this.onCloseNotification(data)}
					containerStyle={{backgroundColor: Colors.GreenLight}}
					imageSrc={require('../assets/circle-check.png')}
				/>
			</View>

		);
	}

	//remove notification from redux state
	onCloseNotification(data) {
		// data = {type, title, message}
		this.props.dispatch(clearNotifications());
		this.setState({notificationVisible: false});
	}

#### Expected Results

The callback is called upon manual dismissal or flicking the alert vertically, but not when the timer expires.

### Additional Information

* React Native version: 0.31.0
* react-native-dropdownalert version: 2.0.0
* Platform(s) (iOS, Android, or both?): both

**Comment by devbriguy** [comment]
Yeah you are right it should be: 
```javascript
closeTimeoutId = setTimeout(function() {
  this.onClose()
}.bind(this), this.props.closeInterval)
```

**Comment by tapdancemobile** [comment]
So, are you telling me to not use the onClose callback and just set my own setTimeout?

**Comment by devbriguy** [comment]
No, there is a bug in the module. It calls `this.dismiss()` inside the timeout but that function has changed to need an argument. I will fix later today and push it out.

**Comment by devBrian** [comment]
@tapdancemobile Use 2.1.0. And so expected is that alert will dismiss automatically after about 4 seconds by default and then onClose prop will fire which will trigger your handler function to proceed with other logic you have there.  Cheers.

**Comment by tapdancemobile** [comment]
Thanks! I have verified - it works great! This is an awesome library - you rock...
Mark
