### ISSUE TITLE
[Android] tap to close not work

### ISSUE THREAD

**Issue by ianlin** [devBrian/react-native-dropdownalert#21]
#### Issue Description

When the dropdown appears, tap the alert does not close it. However if I delete the `{...panResponder.panHandlers}` under `Animated.View`, it works. Seems pan responder is blocking the touch event.

It works as expected on iOS.
#### Steps to Reproduce / Code Snippets

Show an alert with `closeInterval={0}`, and tap the alert.
#### Expected Results

The displayed alert is closed.
#### Additional Information
- React Native version: 0.31.0
- react-native-dropdownalert version: 2.1.0
- Platform(s) (iOS, Android, or both?): Android 4.4.2

**Comment by devBrian** [comment]
Hi @ianlin, I'm unable to reproduce. I'm using the emulator. Are you using a device? One thing that would make the onPress not work is if you have `showCancel={true}` as I have `onPress{(this.props.showCancel) ? null : this.onClose}`. Perhaps this is related to https://github.com/facebook/react-native/issues/3082

**Comment by ianlin** [comment]
Hey @devBrian thanks for replying. Yes I was testing on an Android device without having `showCancel={true}`; didn't test it on the emulator though.

Good news that it works with the solution from [facebook/react-native#3082 (comment)][1], but instead of adding `return gestureState.dx !== 0 && gestureState.dy !== 0` under `onMoveShouldSetPanResponderCapture` I put them in `onMoveShouldSetPanResponder`. Now the dragging/touching event can both response.

[1]: https://github.com/facebook/react-native/issues/3082#issuecomment-191338207

**Comment by devBrian** [comment]
Awesome. I will get this worked in asap. Thanks.

**Comment by teyou** [comment]
hmm i'm still having this issue on Android using the latest version

**Comment by fschai89** [comment]
Some device cant tap, tested on Samsung note 5 not able to tap, but Samsung note 3 able to tap.
