### ISSUE TITLE
[IOS] RN 0.34 warning message when unmounting a view which shows the alert

### ISSUE THREAD

**Issue by ismdcf** [devBrian/react-native-dropdownalert#22]
#### Issue Description

when the view is being unmounted while the dropdown alert is shown shows the following warning

"setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the DropdownAlert component." 
#### Steps to Reproduce / Code Snippets

Mount An view using the navigator and then unmount it while the dropdown is shown
#### Expected Results

No warning should be shown 
### Additional Information
- React Native version: [0.34.0]
- react-native-dropdownalert version: [1.10.0]
- Platform(s) (iOS, Android, or both?): [IOS]

**Comment by devBrian** [comment]
Hi, @ismdcf. Can you share the props you have set? My assumption is that it's trying to close automatically due to the timeout (about 4 seconds default) and since it's unmounted it throws this error.

**Comment by devBrian** [comment]
One suggestion is you can dismiss/close it programmatically like so: 

```javascript
componentWillUnmount() {
  this.dropdown.onClose()
}
```

**Comment by ismdcf** [comment]
Hi ,@devBrian thanks for reply . upgraded dropdown alert to the latest and added this.dropdown.onClose to the componentWillUnmout() function but still getting the same warning .

anything else I might try to fix.

**Comment by devBrian** [comment]
Hi @ismdcf I think I narrowed it down. I see that the dismiss method has another timeout in it and it fires at 450 milliseconds which with the warning seems to be too slow as it's already unmounted and as you can see inside the timeout there is a: 
```javascript
this.setState({
   isOpen: false
})
```
A temporary workaround is to perhaps delay the pop or push or reset by the navigator with use of a timeout and make timeout duration a tad longer than 450 milliseconds if dropdown alert is shown. I will add a fix for this soon.

**Comment by ismdcf** [comment]
Hi @devBrian once again thanks pal.

I did the following on the back press 
` setTimeout(() => {this.props.navigator.pop()},700);`

and added this on the component will unmount 

`this.dropdown.onClose()`

Still getting the same warning

**Comment by devBrian** [comment]
hi @ismdcf 

You can try to remove the `this.drop.onClose()` from unmount as the timeout should be enough if not can you share the props you use and the alert parameters? Thanks

**Comment by devBrian** [comment]
hi @ismdcf can you try the below: 

```javascript
// back onPress
onPress() {
  this.dropdown.onClose() // close it
  setTimeout(() => { // wait a few 
    this.props.navigator.pop() // pop the screen
  }, 700);
}
```
if still no good can you show me dropdown props and code snippet of your onPress? Thanks

**Comment by devBrian** [comment]
Please reopen if warning persists.
