### ISSUE TITLE
Node modules folder is checked in

### ISSUE THREAD

**Issue by jeremyong** [devBrian/react-native-dropdownalert#25]
#### Issue Description

Node modules folder is checked in

**Comment by devBrian** [comment]
Hi @jeremyong 

I think it was needed for the unit tests to run successfully.  I am not 100 % sure if that's the proper way. Just fyi it's ignored in npm installs.

Thanks

**Comment by jeremyong** [comment]
Definitely isn't the proper way. It just means the package.json was missing a dev-dependency marked in order to run the tests and it should just be added. The node-modules folder is picked up, and fetched in fact both with npm and yarnpkg. It's a sizable folder which doubles the fetch time of a project that includes this as a dependency and more importantly, causes conflicts if a later version of react native in installed (a lot of the dependencies in the package.json should have relaxed restrictions and should probably be peer dependencies).

**Comment by devBrian** [comment]
Now that I think about it, I had it so that it would the run tests locally. 

Thanks @jeremyong

**Comment by jeremyong** [comment]
Great thanks!
