### ISSUE TITLE
Alert dismisses if called while still open.

### ISSUE THREAD

**Issue by DmsChrisPena** [devBrian/react-native-dropdownalert#27]
So I'm using the alert for some simple user error handling. It's working fantastic but if the user was to submit the login twice within 4 seconds (the time that I allow the alert to be open) it will disappear and not reappear the 2nd error message. I was able to solve this by making my function async and just await on a timeout depending if the alert is open, but it would be nice if this component had this built in.

Example of what I'm doing.
```javascript
const sleep = (ms) => {
  return new Promise(resolve => setTimeout(resolve, ms));
};

...  async() => {
    // Clear Alert if open
    if (alert.state.isOpen) {
      alert.dismiss();
      await sleep(450);
    }
   ... rest of the function.
}
```

**Comment by DmsChrisPena** [comment]
Actually, my approach does cause problems with mounting and unmounting the timeout. So I do not recommend it. I will post when I figure out a solution to this problem.

**Comment by devBrian** [comment]
Hi @DmsChrisPena So I think I follow your use case. In short, you are dismissing an alert then wanting to follow it up with another? And in a sense there should be a queue system?

**Comment by devBrian** [comment]
Actually a queue system would be a little overkill but instead like a simple replace. 

See this demo (unpublished enhancement): 
![demo](https://cloud.githubusercontent.com/assets/7293079/22394313/efa72310-e4ea-11e6-9a90-fbcb834a2594.gif)

As you can see I tap on each buttons to fire another alert if one is already there I would dismiss and show the next one. I put in a random number to demonstrate the difference between one alert to another. Does this satisfy your use case?

**Comment by devBrian** [comment]
Or do not dismiss and rather state change the open alert, like so: 

![demo2](https://cloud.githubusercontent.com/assets/7293079/22394406/7c5c27b2-e4ee-11e6-9474-6f6dfee608a0.gif)

Which do you think is more useful?

**Comment by devBrian** [comment]
I'm leaning towards a mixture like where if the type is the same then state change else do the replace.

**Comment by DmsChrisPena** [comment]
I do prefer the simple replace to indicate that there is another alert if they happen to both be the same color and type of alert. But I do think both of the styles could be useful so maybe you can make a prop where you can choose between the two. Thanks so much for the response by the way!

**Comment by devBrian** [comment]
Hi @DmsChrisPena Thank you for your feedback. Check out v2.5.0 and the new replaceEnabled prop.
