### ISSUE TITLE
Remove paddingTop by default

### ISSUE THREAD

**Issue by datwheat** [devBrian/react-native-dropdownalert#28]
With `ex-navigation`'s Navbar on iOS, the paddingTop pushed my alert down 20 points too far. It thinks that the bottom of the navbar is the top of the screen and compensates for the statusbar unnecessarily. It would be good to let the developer specify a container style for the non-custom components or specify if they want the paddingTop or not.

**Comment by devBrian** [comment]
hi @datwheat I have not used `ex-navigation` navbar. Can you provide a screenshot or a code snippet? By the way,  there is a prop called `containerStyle` and using this in-conjunction with custom type you can set `paddingTop` to 0. I could expose the defaultContainer or paddingTop if using the containerStyle prop does not have desired results. Hope this helps.

**Comment by datwheat** [comment]
![simulator screen shot jan 29 2017 6 09 31 pm](https://cloud.githubusercontent.com/assets/12488826/22408839/1ffde4b8-e64e-11e6-953b-d71949884464.png)

**Comment by datwheat** [comment]
it also turns the StatusBar light and doesn't go back after dismissed

**Comment by devBrian** [comment]
It looks like it starts below the navbar is that your desired result or you wanting to begin at all the way at the top?

Yes, I have been debating about taking out the statusBar and letting the developer configure it. I could leave it and just add a prop to let the module take control or not.

**Comment by datwheat** [comment]
I want it to start below the navbar, but without the extra 20px of paddingTop. and I want to keep the rest of the default Error styles

**Comment by devBrian** [comment]
Ok so I able to remove the `paddingTop` like so: 
```javascript
<DropdownAlert
    ref={(ref) => this.dropdown = ref}
    containerStyle={{
       backgroundColor: '#cc3232',
       paddingTop: 0
     }}
    imageSrc={require('./assets/error.png')} // see below
// ...
this.dropdown.alert('Error', 'Email username must be provided.')
// ...
 />
```
You will need to head to your node_modules folder and locate react-native-dropdownalert then head to assets folder. After which you want to extract the error pngs and copy it to your local project directory then give that path to `imageSrc` prop.

**Comment by devBrian** [comment]
I forgot to change the text color to white which can be done by adding these props:  

```javascript
titleStyle={{
  color: 'white'
}}
messageStyle={{
  color: 'white'
}}
```

**Comment by datwheat** [comment]
it seems to be white by default, but thanks!

**Comment by devBrian** [comment]
Closing this if you need more help reopen or create a new issue. I am going to add an issue about the StatusBar.

**Comment by NguyenPhatBG** [comment]
I'm remove default paddingTop, like @FiberJW described, so now Can I do something?
![capture6](https://user-images.githubusercontent.com/33904172/46122969-01e3b680-c246-11e8-8aef-7627e019bf90.PNG)
![capture5](https://user-images.githubusercontent.com/33904172/46122975-07d99780-c246-11e8-9158-1d4a672fdf01.PNG)
![capture4](https://user-images.githubusercontent.com/33904172/46122978-0b6d1e80-c246-11e8-8bdb-bdf8c44d07ba.PNG)
my code here!
