### ISSUE TITLE
[Android] Status bar backgroundColor is needed

### ISSUE THREAD

**Issue by devbriguy** [devBrian/react-native-dropdownalert#5]
See: https://facebook.github.io/react-native/docs/statusbar.html

**Comment by devBrian** [comment]
Can you provide a use case?

**Comment by devBrian** [comment]
I'll do some tests on Android and see what's going on with statusBar.

**Comment by devBrian** [comment]
You have access to the statusBar background color if you have statusBar in your parent component which contains this component. Even if you set it to hidden the background color you provide will render when this component appears. During my testing I did stumble upon a minor bug that I will create a different issue for.
