### ISSUE TITLE
Look into zIndex as a possible replacement of modal

### ISSUE THREAD

**Issue by devBrian** [devBrian/react-native-dropdownalert#7]
- https://developer.mozilla.org/en-US/docs/Web/CSS/z-index
- http://facebook.github.io/react-native/releases/0.29/docs/layout-props.html

Although if used this might mean react-native target would need to be >=0.29.

**Comment by devBrian** [comment]
Keeping a close eye on this.

**Comment by teyou** [comment]
does it mean that by using zIndex:
1. user doesn't need to tap on the DropdownAlert in order to close it?
2. when showing DropdowAlert, user still be able to tap anywhere else?

**Comment by devBrian** [comment]
@teyou 1. No but you can provide a closeInterval to close automatically 2. Yes it allows user interaction to the rest of the screen.

**Comment by teyou** [comment]
cool, I think we should implement zIndex to improve the User Experience.
Keep the good work, @devBrian !

**Comment by devBrian** [comment]
So some news, to support zIndex for both platforms RN >= 0.30.

**Comment by devBrian** [comment]
Experimented with it and it's just not overlapping other UI. I will keep trying though.

**Comment by devBrian** [comment]
So zIndex is not the solution but instead by adding these styles to the animated view: 
```
position: 'absolute', top: 0, left: 0, right: 0
```
Then moving the dropdownAlert to the last position in the document tree, like so:

```
<View>
  <Text> </Text>
// ...
  <DropdownAlert />
</View
```
I was able to get the desired result.
