### ISSUE TITLE
Fire event when alert is closed

### ISSUE THREAD

**Issue by jbrodriguez** [devBrian/react-native-dropdownalert#8]
Right now, if you leave the alert open (closeInterval={0}), you don't know when the user closes the alert (tap).

The suggestion have an onHide/onClose prop, which is a user defined callback.

The use case is for flows like redux, which would define this callback to change state accordingly (set error state to empty/null).

**Comment by devBrian** [comment]
Indeed good idea. I will add a prop like ```onClose()``` and pass properties of the open alert. I will fire it for alerts that close either with interval or not.
